### ISSUE TITLE
When do you release the whole source code for this project?

### ISSUE THREAD

**Issue by Rango-T10000** [HR-zju/LiCROcc#1]
Excellent work! This performace is amazing,
When do you release the whole source code for this project?
I am really looking forward to that.

**Comment by HR-zju** [comment]
> Excellent work! This performace is amazing, When do you release the whole source code for this project? I am really looking forward to that.

Hi, thanks for your interest. We have posted our code on github, you can check it out here: https://github.com/HR-zju/LiCROcc.git
