### ISSUE TITLE
Question about the code: "ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'"

### ISSUE THREAD

**Issue by Rango-T10000** [HR-zju/LiCROcc#2]
Hi, according to your instruction, I am trying to run the eval code. And I met the following question:
When I try to run the eval command:"./tools/dist_test.sh ./projects/configs/ssc_rs/ssc_rs_base_nuscenes_LC2LR123.py ckpts/RC-LiCROcc.pth 1", the error is:
<img width="1569" alt="image" src="https://github.com/user-attachments/assets/526f2dd7-bc3c-4e1b-a3fd-248da2bbca99">

**Comment by HR-zju** [comment]
> Hi, according to your instruction, I am trying to run the eval code. And I met the following question: When I try to run the eval command:"./tools/dist_test.sh ./projects/configs/ssc_rs/ssc_rs_base_nuscenes_LC2LR123.py ckpts/RC-LiCROcc.pth 1", the error is: <img alt="image" width="1569" src="https://private-user-images.githubusercontent.com/89722605/392318642-526f2dd7-bc3c-4e1b-a3fd-248da2bbca99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzE5NDcsIm5iZiI6MTczMzMzMTY0NywicGF0aCI6Ii84OTcyMjYwNS8zOTIzMTg2NDItNTI2ZjJkZDctYmMzYy00ZTFiLWEzZmQtMjQ4ZGEyYmJjYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3MDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OGY1YTFmNTIxMzg1NGI5N2M5N2M2N2UzMWYwODA4M2QyMjBkNGU0NWI5ZWQ1NmE3NmRmYTlmYjM4NWY5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._MtfE7AuyoZShjxu4beTrkT8o1Ithdm2qIGQPDGV5m0">

Hi,

Thank you for your feedback! We noticed that this is an accidentally uploaded unrelated file. We've released a more streamlined version, and we recommend downloading and trying out the new version.

If you have any further questions, please feel free to reach out!

Thanks!

**Comment by Rango-T10000** [comment]
> > Hi, according to your instruction, I am trying to run the eval code. And I met the following question: When I try to run the eval command:"./tools/dist_test.sh ./projects/configs/ssc_rs/ssc_rs_base_nuscenes_LC2LR123.py ckpts/RC-LiCROcc.pth 1", the error is: <img alt="image" width="1569" src="https://private-user-images.githubusercontent.com/89722605/392318642-526f2dd7-bc3c-4e1b-a3fd-248da2bbca99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzE5NDcsIm5iZiI6MTczMzMzMTY0NywicGF0aCI6Ii84OTcyMjYwNS8zOTIzMTg2NDItNTI2ZjJkZDctYmMzYy00ZTFiLWEzZmQtMjQ4ZGEyYmJjYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3MDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OGY1YTFmNTIxMzg1NGI5N2M5N2M2N2UzMWYwODA4M2QyMjBkNGU0NWI5ZWQ1NmE3NmRmYTlmYjM4NWY5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._MtfE7AuyoZShjxu4beTrkT8o1Ithdm2qIGQPDGV5m0">
> 
> Hi,
> 
> Thank you for your feedback! We noticed that this is an accidentally uploaded unrelated file. We've released a more streamlined version, and we recommend downloading and trying out the new version.
> 
> If you have any further questions, please feel free to reach out!
> 
> Thanks!

Hi, I met a new error about spconv.
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/c1d76cb2-ddf8-4bd0-b1f3-f85aa0c10de5">
It seems this my installed spconv can not support the GPU implement.
Here are the versions:
<img width="579" alt="image" src="https://github.com/user-attachments/assets/5c0d2524-9e98-4976-a298-4d1bd8c07154">


Can you make sure about which one should be installed and which version of spconv should be chosen?
Because in your requirement there is only spconv-cu111.

**Comment by Rango-T10000** [comment]
@HR-zju

**Comment by HR-zju** [comment]
> @HR-zju

Hi, You can install spconv with the following command: 
`spconv-cu111==2.1.25`

**Comment by Rango-T10000** [comment]
> > @HR-zju
> 
> Hi, You can install spconv with the following command: `pip install spconv-cu111==2.1.25`

Hi, but I have already installed the spconv-cu111==2.1.25.

**Comment by HR-zju** [comment]
> > > @HR-zju
> > 
> > 
> > Hi, You can install spconv with the following command: `pip install spconv-cu111==2.1.25`
> 
> Hi, but I have already installed the spconv-cu111==2.1.25.


I think remove 'spconv' is helpful.
`pip uninstall spconv`
`pip install spconv-cu111==2.1.25`

**Comment by Rango-T10000** [comment]
> > @HR-zju @Rango-T10000
> 
> Hi, You can install spconv with the following command: `pip uninstall spconv` `pip install spconv-cu111==2.1.25`

If I uninstall the spconv and only insatll spconv-cu111==2.1.25, there will be a new error:
<img width="1192" alt="image" src="https://github.com/user-attachments/assets/9fe2c7fb-eef3-48c5-848c-997a73daa889">

**Comment by HR-zju** [comment]
> > > @HR-zju @Rango-T10000
> > 
> > 
> > Hi, You can install spconv with the following command: `pip uninstall spconv` `pip install spconv-cu111==2.1.25`
> 
> If I uninstall the spconv and only insatll spconv-cu111==2.1.25, there will be a new error: <img alt="image" width="1192" src="https://private-user-images.githubusercontent.com/89722605/392683753-9fe2c7fb-eef3-48c5-848c-997a73daa889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODEwOTksIm5iZiI6MTczMzM4MDc5OSwicGF0aCI6Ii84OTcyMjYwNS8zOTI2ODM3NTMtOWZlMmM3ZmItZWVmMy00OGM1LTg0OGMtOTk3YTczZGFhODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA2Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNzZiMzk0MTYzOTdjZjZhM2JmZjE2NDM3NGY1YmE4ZjE2MWExMDYyNWU2OGQ0NzUwMjc3YzUwNWZmYjAzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n5FSTb6VVP0VlUs0us7YyP8oi4QKRa-KgSQbM2ddFCM">

It works for me. Make sure the spconv-cu111 was installed.
![image](https://github.com/user-attachments/assets/84a4b42f-b48e-43bd-b314-ff971735401c)

**Comment by Rango-T10000** [comment]
> > > > @HR-zju @Rango-T10000
> > > 
> > > 
> > > Hi, You can install spconv with the following command: `pip uninstall spconv` `pip install spconv-cu111==2.1.25`
> > 
> > 
> > If I uninstall the spconv and only insatll spconv-cu111==2.1.25, there will be a new error: <img alt="image" width="1192" src="https://private-user-images.githubusercontent.com/89722605/392683753-9fe2c7fb-eef3-48c5-848c-997a73daa889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODEwOTksIm5iZiI6MTczMzM4MDc5OSwicGF0aCI6Ii84OTcyMjYwNS8zOTI2ODM3NTMtOWZlMmM3ZmItZWVmMy00OGM1LTg0OGMtOTk3YTczZGFhODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA2Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNzZiMzk0MTYzOTdjZjZhM2JmZjE2NDM3NGY1YmE4ZjE2MWExMDYyNWU2OGQ0NzUwMjc3YzUwNWZmYjAzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n5FSTb6VVP0VlUs0us7YyP8oi4QKRa-KgSQbM2ddFCM">
> 
> It works for me. Make sure the spconv-cu111 was installed. ![image](https://private-user-images.githubusercontent.com/73371574/392684713-84a4b42f-b48e-43bd-b314-ff971735401c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODEzMTQsIm5iZiI6MTczMzM4MTAxNCwicGF0aCI6Ii83MzM3MTU3NC8zOTI2ODQ3MTMtODRhNGI0MmYtYjQ4ZS00M2JkLWIzMTQtZmY5NzE3MzU0MDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmYxYzUyMWUwMDA2YjI2OTEyZGVjNzliNTY1M2RhZDY2OThhMWJlMTljYjZjYzdjZGQ4OTFjNWE3ODBkMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bcX_zrKzutUeNVcpMQ05pyVVchKLJIY2a7UEcpCBiIs)

Thanks for your instruction. I think I can run the eval code successfully. 
However, I met some warning and I am not sure if it will make something wrong:
<img width="1484" alt="image" src="https://github.com/user-attachments/assets/7d3439ba-f7ee-454f-af9e-94ec338f6060">


And I have another problem that this eval result just gives some bechmark?
Will it keep the prediction results? I mean the results of semantic occupancy in a .pkl or .npy format, which can be used for  visualiztion.

**Comment by Rango-T10000** [comment]
This eval result just gives some bechmark:
<img width="1477" alt="image" src="https://github.com/user-attachments/assets/9752ec10-a3ce-4773-8a46-62ea3219ba8e">

Will you provide the prediction and visualization code? 
I mean the results of semantic occupancy in a .pkl or .npy format, which can be used for visualiztion.

**Comment by HR-zju** [comment]
> This eval result just gives some bechmark: <img alt="image" width="1477" src="https://private-user-images.githubusercontent.com/89722605/392801746-9752ec10-a3ce-4773-8a46-62ea3219ba8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDkzMTcsIm5iZiI6MTczMzQwOTAxNywicGF0aCI6Ii84OTcyMjYwNS8zOTI4MDE3NDYtOTc1MmVjMTAtYTNjZS00NzczLThhNDYtNjJlYTMyMTliYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MzAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDM2ODBiZjkwNmUzN2VhOTQ4OGMyYzg1MjVmMjJiMGI0NWNiYmNhNWM3NzZiZDgxMzk3YjU0MDYxODJiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ScSovVpgWng5B6mFb5UbM8XfJPsHvEVKidtvy_tKG8">
> 
> Will you provide the prediction and visualization code? I mean the results of semantic occupancy in a .pkl or .npy format, which can be used for visualiztion.

Temporarily only support saving occupancy predictions (refer to [MonoScene](https://github.com/astra-vision/MonoScene#visualization) for visualization tools)
```bash
bash run_eval.sh $PATH_TO_CFG $PATH_TO_CKPT $GPU_NUM --show --show-dir $PATH
```

**Comment by Rango-T10000** [comment]
> > This eval result just gives some bechmark: <img alt="image" width="1477" src="https://private-user-images.githubusercontent.com/89722605/392801746-9752ec10-a3ce-4773-8a46-62ea3219ba8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDkzMTcsIm5iZiI6MTczMzQwOTAxNywicGF0aCI6Ii84OTcyMjYwNS8zOTI4MDE3NDYtOTc1MmVjMTAtYTNjZS00NzczLThhNDYtNjJlYTMyMTliYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MzAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDM2ODBiZjkwNmUzN2VhOTQ4OGMyYzg1MjVmMjJiMGI0NWNiYmNhNWM3NzZiZDgxMzk3YjU0MDYxODJiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ScSovVpgWng5B6mFb5UbM8XfJPsHvEVKidtvy_tKG8">
> > Will you provide the prediction and visualization code? I mean the results of semantic occupancy in a .pkl or .npy format, which can be used for visualiztion.
> 
> Temporarily only support saving occupancy predictions (refer to [MonoScene](https://github.com/astra-vision/MonoScene#visualization) for visualization tools)
> 
> ```shell
> bash run_eval.sh $PATH_TO_CFG $PATH_TO_CKPT $GPU_NUM --show --show-dir $PATH
> ```

Hello, I found that there is no run_eval.sh file in your project.

**Comment by HR-zju** [comment]
> > > This eval result just gives some bechmark: <img alt="image" width="1477" src="https://private-user-images.githubusercontent.com/89722605/392801746-9752ec10-a3ce-4773-8a46-62ea3219ba8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDkzMTcsIm5iZiI6MTczMzQwOTAxNywicGF0aCI6Ii84OTcyMjYwNS8zOTI4MDE3NDYtOTc1MmVjMTAtYTNjZS00NzczLThhNDYtNjJlYTMyMTliYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MzAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDM2ODBiZjkwNmUzN2VhOTQ4OGMyYzg1MjVmMjJiMGI0NWNiYmNhNWM3NzZiZDgxMzk3YjU0MDYxODJiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7ScSovVpgWng5B6mFb5UbM8XfJPsHvEVKidtvy_tKG8">
> > > Will you provide the prediction and visualization code? I mean the results of semantic occupancy in a .pkl or .npy format, which can be used for visualiztion.
> > 
> > 
> > Temporarily only support saving occupancy predictions (refer to [MonoScene](https://github.com/astra-vision/MonoScene#visualization) for visualization tools)
> > ```shell
> > bash run_eval.sh $PATH_TO_CFG $PATH_TO_CKPT $GPU_NUM --show --show-dir $PATH
> > ```
> 
> Hello, I found that there is no run_eval.sh file in your project.
```shell
./tools/dist_test.sh $PATH_TO_CFG $PATH_TO_CKPT $GPU_NUM --show --show-dir $PATH
```
